version: '3.8'

services:
  app:
    build: .
    container_name: timestamp-app
    restart: always
    depends_on:
      - mysql
    volumes:
      - ./logs:/var/log/myapp
    healthcheck:
      test: ["CMD", "pgrep", "bash"]
      interval: 5s
      retries: 3

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: myappdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot123"]
      interval: 10s
      retries: 3
      timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"

volumes:
  db_data:

